name: rms-consumer-2
recipe: wordpress
config:
  webroot: wordpress
  php: '8.2'
  database: mariadb:10.6

services:
  appserver:
    overrides:
      volumes:
        - ../../:/app/wordpress/wp-content/plugins/remote-media-source
      extra_hosts:
        - "rms-source.lndo.site:host-gateway"

tooling:
  wp:
    service: appserver
    cmd: wp --allow-root
